// Hardware smoke/measurement: uses Chrome's actual adapter, never forces a software GPU.
import {chromium} from 'playwright';import fs from 'node:fs';
const out=process.argv[2];const browser=await chromium.launch({channel:'chrome',headless:true});
try { const page=await browser.newPage({viewport:{width:1280,height:720}});await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('we13-quality','medium'));await page.goto('http://127.0.0.1:8000/#stil=quiet',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__app?.apartment&&!window.__app.viewer.suspended,null,{timeout:300000});
page.on('pageerror',e=>console.error('PAGEERROR',e.message));
console.log('hardware',await page.evaluate(async()=>{const adapter=await navigator.gpu?.requestAdapter();const c=document.createElement('canvas').getContext('webgl2');const ext=c?.getExtension('WEBGL_debug_renderer_info');return {webgpu:adapter ? {vendor:adapter.info.vendor,architecture:adapter.info.architecture,device:adapter.info.device,description:adapter.info.description} : null,webgl:ext?c.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,backend:window.__app.viewer.backend,quality:window.__app.viewer.quality};}));
await page.evaluate(async n=>{const v=window.__app.viewer;if(n)v.photoOverride={samples:n};v.goto('living',false);await v.applyMood('golden');window.__hwStarted=performance.now();v.setRenderMode('photo');},Number(process.env.SAMPLES)||0);
await page.waitForFunction(()=>window.__app.viewer.photo?.samples>=1||window.__app.viewer.photo?.state==='error',null,{timeout:300000});console.log('first sample',await page.evaluate(()=>({ms:Math.round(performance.now()-window.__hwStarted),status:window.__app.viewer.photo.status()})));
await page.waitForFunction(()=>window.__app.viewer.photo?.state==='done'||window.__app.viewer.photo?.state==='error',null,{timeout:600000});console.log('finished',await page.evaluate(()=>({ms:Math.round(performance.now()-window.__hwStarted),status:window.__app.viewer.photo.status(),denoiser:!!window.__app.viewer.photo.denoiser,exposure:window.__app.viewer.photo.exposure,portals:window.__app.viewer.photo.scene.children.filter(o=>o.userData.portal).map(o=>({room:o.userData.room,visible:o.visible,intensity:o.intensity,color:o.color.toArray()})),canvas:[window.__app.viewer.photo.renderer.domElement.width,window.__app.viewer.photo.renderer.domElement.height]})));
if(await page.evaluate(()=>window.__app.viewer.photo.state==='error'))throw Error('Hardware photo failed');if(out){const png=await page.evaluate(()=>window.__app.viewer.screenshot());const raw=await page.evaluate(()=>window.__app.viewer.photo.renderer.domElement.toDataURL('image/png'));fs.writeFileSync(out+'/golden-hardware-raw.png',Buffer.from(raw.split(',')[1],'base64'));fs.writeFileSync(out+'/golden-hardware.png',Buffer.from(png.split(',')[1],'base64'));}
}finally{await browser.close();}
